export const API_ENDPOINTS = {
  auth: { login: '/auth/login', me: '/auth/me', logout: '/auth/logout' },
  accounts: '/accounts',
  accountingPeriods: '/accounting-periods',
  customers: '/customers',
  suppliers: '/suppliers',
  items: '/items',
  warehouses: '/warehouses',
  units: '/units',
  taxCodes: '/tax-codes',
  costCenters: '/cost-centers',
  projects: '/projects',
  bankAccounts: '/bank-accounts',
  users: '/users',
  roles: '/roles',
  permissions: '/permissions',
  settings: '/settings',
  auditLogs: '/audit-logs',
  errorLogs: '/error-logs',
  backups: '/backups',
  attachments: '/attachments',
  imports: '/imports',
  transactions: '/transactions',
  inventoryStock: '/inventory/stock',
  inventoryCard: '/inventory/card',
  dashboard: '/dashboard/summary',
  trialBalance: '/reports/trial-balance',
} as const
