<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { Eye, Pencil, Plus, Search } from 'lucide-vue-next'
import { useRouter } from 'vue-router'
import AppBadge from '@/components/common/AppBadge.vue'; import AppButton from '@/components/common/AppButton.vue'; import AppEmptyState from '@/components/common/AppEmptyState.vue'; import AppPagination from '@/components/common/AppPagination.vue'; import AppBreadcrumb from '@/components/layout/AppBreadcrumb.vue'
import { salesInvoiceService } from '@/services/sales-invoice.service'; import { useAuthStore } from '@/stores/auth.store'; import type { SalesInvoice, SalesInvoiceStatus } from '@/types/sales'; import { getApiErrorMessage } from '@/utils/error'
const router=useRouter(),auth=useAuthStore(); const rows=ref<SalesInvoice[]>([]),total=ref(0),page=ref(1),search=ref(''),status=ref(''),loading=ref(false),error=ref('')
const labels:Record<SalesInvoiceStatus,string>={draft:'Draft',pending_approval:'Menunggu Persetujuan',approved:'Disetujui',rejected:'Ditolak',posted:'Posted',partially_paid:'Dibayar Sebagian',paid:'Lunas',reversed:'Reversed',cancelled:'Dibatalkan'}
const tone=(value:SalesInvoiceStatus):'green'|'amber'|'red'|'blue'|'slate'=>value==='paid'||value==='posted'?'green':value==='approved'?'blue':value==='pending_approval'||value==='partially_paid'?'amber':value==='rejected'||value==='cancelled'||value==='reversed'?'red':'slate'
const money=(value:string|number,currency='IDR')=>new Intl.NumberFormat('id-ID',{style:'currency',currency,maximumFractionDigits:2}).format(Number(value)); const date=(value:string)=>new Intl.DateTimeFormat('id-ID',{dateStyle:'medium'}).format(new Date(`${value.slice(0,10)}T00:00:00`))
const load=async()=>{loading.value=true;error.value='';try{const result=await salesInvoiceService.list({page:page.value,limit:20,search:search.value||undefined,status:status.value||undefined});rows.value=result.data;total.value=result.meta.total}catch(e){error.value=getApiErrorMessage(e,'Sales invoice gagal dimuat.')}finally{loading.value=false}}
let timer:number|undefined;watch(search,()=>{clearTimeout(timer);timer=window.setTimeout(()=>{page.value=1;load()},350)});watch(status,()=>{page.value=1;load()});onMounted(load)
</script>
<template><div><AppBreadcrumb/><div class="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h1 class="text-2xl font-bold">Sales Invoice</h1><p class="mt-1 text-sm text-slate-500">Kelola penagihan, persetujuan, posting, dan saldo piutang pelanggan.</p></div><AppButton v-if="auth.hasPermission('sales-invoices.create')" :icon="Plus" @click="router.push('/sales/invoices/new')">Buat Invoice</AppButton></div><section class="panel overflow-hidden"><div class="flex flex-wrap gap-3 border-b p-4"><label class="relative min-w-56 flex-1"><Search class="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input v-model="search" class="field pl-9" placeholder="Cari nomor, pelanggan, referensi..."/></label><select v-model="status" class="field max-w-56"><option value="">Semua status</option><option v-for="(label,key) in labels" :key="key" :value="key">{{label}}</option></select></div><p v-if="error" class="m-4 rounded bg-red-50 p-3 text-sm text-red-700">{{error}}</p><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="p-3">Nomor</th><th class="p-3">Tanggal/Jatuh Tempo</th><th class="p-3">Pelanggan</th><th class="p-3 text-right">Total</th><th class="p-3 text-right">Outstanding</th><th class="p-3">Status</th><th class="p-3"></th></tr></thead><tbody v-if="loading"><tr v-for="i in 5" :key="i"><td colspan="7" class="p-4"><div class="h-5 animate-pulse rounded bg-slate-100"/></td></tr></tbody><tbody v-else class="divide-y"><tr v-for="row in rows" :key="row.id" class="hover:bg-slate-50"><td class="p-3 font-mono font-semibold text-blue-700">{{row.invoice_number}}</td><td class="p-3">{{date(row.invoice_date)}}<small class="block text-slate-500">{{date(row.due_date)}}</small></td><td class="p-3"><b>{{row.customer_name}}</b><small class="block text-slate-500">{{row.customer_code}}</small></td><td class="p-3 text-right">{{money(row.grand_total,row.currency)}}</td><td class="p-3 text-right font-semibold">{{money(row.outstanding_amount,row.currency)}}</td><td class="p-3"><AppBadge :tone="tone(row.status)">{{labels[row.status]}}</AppBadge></td><td class="p-3"><div class="flex justify-end"><button class="rounded p-2 hover:bg-slate-100" @click="router.push(`/sales/invoices/${row.id}`)"><Eye class="h-4 w-4"/></button><button v-if="['draft','rejected'].includes(row.status)&&!row.sales_order_id&&auth.hasPermission('sales-invoices.update')" class="rounded p-2 hover:bg-slate-100" @click="router.push(`/sales/invoices/${row.id}/edit`)"><Pencil class="h-4 w-4"/></button></div></td></tr></tbody></table></div><AppEmptyState v-if="!loading&&!rows.length&&!error" title="Belum ada sales invoice" description="Buat invoice pertama atau ubah filter pencarian."/><div class="border-t p-4"><AppPagination :page="page" :total="total" :per-page="20" @change="page=$event;load()"/></div></section></div></template>
